[project]
name = "fpsanticheat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.129.0",
    "opencv-python>=4.13.0.92",
    "python-dotenv>=1.2.1",
    "uvicorn>=0.41.0",
]
